### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'connect')

### ISSUE THREAD

**Issue by andriy-panchiy** [bbird1980/vuex-extension-sync#1]
Здраствуйте, у меня часто возникает ошибка:
`TypeError: Cannot read properties of undefined (reading 'connect')`

Если встречали эту ошибку, или знаете как исправить, буду рад любой помощи. 
Буду очень благодарен, если вы свяжитесь со мной. Мой телеграмм прикреплен в профиле. Спасибо!

**Comment by andriy-panchiy** [comment]
Как я узнал ранее, в коде файла index.mjs используется chrome.runtime.connect:
```
  connect(r = !1) {
    this.port = chrome.runtime.connect({ name: this.connectionName }), this.port.onMessage.addListener(this.onMessage.bind(this)), this.port.onDisconnect.addListener(() => {
      this.connect(!0);
    }), r && this.store.commit(dt);
  }
```
Но исходя из этой [статьи](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/tCWVZRq77cg/m/KB6-tvCdAgAJ) chrome.runtime прекратил определяться на всех страницах с 106 версии chrome, для этого нужно прописывать в manifest дополнительное поле:
```
  "externally_connectable": {
    "matches": ["http://somesite.com/*"]
  },
```
Прописав дополнительно это в manifest, chrome.runtime начал работать на нужных вкладках, и ошибка изменилась на:
`(index.mjs:73 Uncaught TypeError: Error in invocation of runtime.connect(optional string extensionId, optional object connectInfo): chrome.runtime.connect() called from a webpage must specify an Extension ID)`

Ошибка указывает на то что для использования метода `connect` нужно передать tabId.

Есть ли возможно её как то исправить?

**Comment by bbird1980** [comment]
Привет, если я правильно понимаю, то достаточно в манифесте использовать `host_permissions`, т.к. у меня в расширении, из которого эта либа и родилась, никаких `externally_connectable` не было и нет, однако все успешно работает.

**Comment by andriy-panchiy** [comment]
Да, спасибо, это помогло! У меня в host_permissions не было прописано доступ ко всем ссылкам, а только к тем с которыми нужно взаимодействовать.
