### ISSUE TITLE
[onMutation] Not initialized yet

### ISSUE THREAD

**Issue by ZaifSenpai** [bbird1980/vuex-extension-sync#2]
I am trying to implement this in my project but I get this error
`[33mWARN[0m: [vuex-extension-sync][Page] [page_2kf5h9q][onMutation] Not initialized yet`

<img width="1027" alt="image" src="https://github.com/bbird1980/vuex-extension-sync/assets/16265942/a6dc800b-8d20-48fe-ae4d-e01aea25dbcd">

This is how I initialized it:
```
plugins: [
  VuexExtensionSync({
    persist: ["somePersistedKey"],
    ignore: [],
    debug: false,
  }),
],
```

**Comment by bbird1980** [comment]
I see red error on screenshot because of service worker is not active (maybe slept by inactivity), so page script didn't received sync event from bg script and added to pending mutations queue until sync will be received.

**Comment by ZaifSenpai** [comment]
can you share a complete example project for using this vuex plugin?

**Comment by bbird1980** [comment]
Pushed [example/extension](https://github.com/bbird1980/vuex-extension-sync/tree/main/example/extension)
